// Generates src/shared/tacosTown.generated.ts from scripts/tacos-meshes.json
// (produced by tacos-dump.ts). All coords are Tacos-LOCAL metres; map.ts
// translates by the town anchor. Colliders are 2D AABBs for shared physics.
import { readFileSync, writeFileSync } from 'node:fs'

interface Box { minX: number; minZ: number; maxX: number; maxZ: number }
interface MeshRow { name: string; mat: string; min: number[]; max: number[]; walls?: Box[] }
const data = JSON.parse(readFileSync('scripts/tacos-meshes.json', 'utf8')) as {
  total: { min: number[]; max: number[] }
  meshes: MeshRow[]
}

// west-row meshes removed to open the main-street entry from the highway stub
const HIDDEN = ['buildings_21003', 'buildings_03002']

// asphalt corridors measured from the Road* meshes (straight segments)
const NS_BANDS: Array<[number, number]> = [[-82.0, -59.1], [6.0, 25.9], [94.0, 113.9]]
const EW_BANDS: Array<[number, number]> = [[-107.6, -87.7], [-19.6, 2.2], [68.4, 88.3]]
const ROAD_X: [number, number] = [-82.0, 113.9]
const ROAD_Z: [number, number] = [-107.6, 88.3]

const inBand = (v: number, bands: Array<[number, number]>) => bands.some(([a, b]) => v >= a && v <= b)
const onAsphalt = (x: number, z: number) =>
  (inBand(x, NS_BANDS) && z >= ROAD_Z[0] && z <= ROAD_Z[1]) ||
  (inBand(z, EW_BANDS) && x >= ROAD_X[0] && x <= ROAD_X[1])

const SOLID_PREFIX = /^(buildings|OXXO|Fence|brick|doors_|gas_tank|Public_phone|trash_can|Refrigerator|Board|Taco_stand)/
const POLE_PREFIX = /^(electric_pole|Parking_M)/

// anything a car simply rides over: kerbs, painted markers, wheel stops
const RIDE_OVER_H = 0.6

const colliders: Array<{ minX: number; minZ: number; maxX: number; maxZ: number }> = []
const paved: Box[] = [] // forecourts/slabs: tarmac grip, and nothing scatters onto them
const skipped: string[] = []
for (const m of data.meshes) {
  if (HIDDEN.includes(m.name)) continue
  const [minX, minY, minZ] = m.min
  const [maxX, maxY, maxZ] = m.max
  const w = maxX - minX, h = maxY - minY, d = maxZ - minZ

  // dumped wall boxes (mesh merges a building with ground it doesn't occupy —
  // OXXO's AABB otherwise walls off its whole parking lot). The AABB is still
  // useful as the paved footprint: it's the building plus its own slab.
  if (m.walls) {
    colliders.push(...m.walls)
    paved.push({ minX, minZ, maxX, maxZ })
    continue
  }
  if (maxY < RIDE_OVER_H) { skipped.push(`${m.name} (ride-over, ${maxY.toFixed(1)}m tall)`); continue }

  if (/^Tree/.test(m.name)) {
    // trunk-sized box like the game's trees
    const cx = (minX + maxX) / 2, cz = (minZ + maxZ) / 2
    colliders.push({ minX: cx - 0.7, minZ: cz - 0.7, maxX: cx + 0.7, maxZ: cz + 0.7 })
    continue
  }
  if (/^Parking_M/.test(m.name)) {
    // rows of parking meters: thin strips along the kerb — solid
    if (minY > 1.5) continue
    colliders.push({ minX, minZ, maxX, maxZ })
    continue
  }
  if (POLE_PREFIX.test(m.name)) {
    // power poles carry wide crossarms — the AABB would wall the sidewalk; skip
    if (w > 1.6 || d > 1.6) { skipped.push(`${m.name} (pole span ${w.toFixed(1)}x${d.toFixed(1)})`); continue }
    if (minY > 1.5) continue
    colliders.push({ minX, minZ, maxX, maxZ })
    continue
  }
  if (!SOLID_PREFIX.test(m.name)) continue
  // must reach car height and be substantial
  if (minY > 1.5 || maxY < 1.0 || w < 0.12 || d < 0.12) { skipped.push(`${m.name} (small/high)`); continue }
  // street furniture (taco stand, phone, fridge, fence…) legitimately sits in the
  // parking lanes — only big building-class meshes must stay off the asphalt
  if (/^(buildings|OXXO)/.test(m.name) && onAsphalt((minX + maxX) / 2, (minZ + maxZ) / 2)) {
    skipped.push(`${m.name} (on asphalt!)`)
    continue
  }
  colliders.push({ minX, minZ, maxX, maxZ })
}

// street lights: heads of the Light* meshes; height = head centre y
const lamps = data.meshes
  .filter((m) => /^Light/.test(m.name))
  .map((m) => ({
    x: +(((m.min[0] + m.max[0]) / 2).toFixed(2)),
    z: +(((m.min[2] + m.max[2]) / 2).toFixed(2)),
    h: +(((m.min[1] + m.max[1]) / 2).toFixed(2)),
  }))

const round = (v: number) => +v.toFixed(2)
const out = `// GENERATED by scripts/tacos-gen.ts — do not edit by hand.
// Tacos town set piece, LOCAL coords (metres). map.ts translates by the anchor.
export interface TacosBox { minX: number; minZ: number; maxX: number; maxZ: number }

export const TACOS_BOUNDS = { minX: ${round(data.total.min[0])}, minZ: ${round(data.total.min[2])}, maxX: ${round(data.total.max[0])}, maxZ: ${round(data.total.max[2])} }

// asphalt corridors (street grid measured off the Road* meshes)
export const TACOS_NS_BANDS: Array<[number, number]> = ${JSON.stringify(NS_BANDS)}
export const TACOS_EW_BANDS: Array<[number, number]> = ${JSON.stringify(EW_BANDS)}
export const TACOS_ROAD_X: [number, number] = ${JSON.stringify(ROAD_X)}
export const TACOS_ROAD_Z: [number, number] = ${JSON.stringify(ROAD_Z)}

// paved lots (a shell mesh's own slab): drivable tarmac, and off-limits to the
// tree scatter — without this, trees sprout across the OXXO forecourt
export const TACOS_PAVED: TacosBox[] = ${JSON.stringify(paved)}

// meshes hidden client-side to open the west entry (their colliders are dropped too)
export const TACOS_HIDDEN: string[] = ${JSON.stringify(HIDDEN)}

// street-lamp heads (x, z, head height)
export const TACOS_LAMPS: Array<{ x: number; z: number; h: number }> = ${JSON.stringify(lamps)}

export const TACOS_COLLIDERS: TacosBox[] = [
${colliders.map((c) => `  { minX: ${round(c.minX)}, minZ: ${round(c.minZ)}, maxX: ${round(c.maxX)}, maxZ: ${round(c.maxZ)} },`).join('\n')}
]
`
writeFileSync('src/shared/tacosTown.generated.ts', out)
console.log(`colliders: ${colliders.length}, lamps: ${lamps.length}`)
console.log('skipped:', skipped.join('; ') || 'none')
